name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  file-path:  # path of the file 
    description: 'Set the file path directory'
    required: true
    default: '/'

  file-name: # input filename
    description: 'Set the filename'
    required: true
    default: '.yml'

outputs:
  fullPath: # full path id
    description: 'Output full file path'
runs:
  using: 'node12'
  main: 'dist/index.js'