on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to get filename and path
    steps:
    - name: Get full path step
      id: get-path
      uses: eibay/update-file-actions@main
      with:
        file-path: 'infrastructure'
        file-name: 'values.yml'
      run: |
        pwd

    # Use the output from the `hello` step
    - name: Get the full path
      run: echo "The full path was ${{ steps.get-path.outputs.full-path }}"